import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {




    return <>
        {children}
    </>
}

//  https://vercel.com/blog/introducing-the-vercel-ai-sdk
//  https://ollama.com/blog/openai-compatibility
//  https://github.com/jakobhoeg/nextjs-ollama-llm-ui/tree/master/src/app/api/model